---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  retries: 5
  delay: 10
  register: nginx_install
  until: nginx_install is succeeded

- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  retries: 3
  delay: 5
  register: nginx_service
  until: nginx_service is succeeded