---
- name: Install Nginx
  hosts: all
  remote_user: root
  become: false

  roles:
    - nginx

- name: Install Git
  hosts: all
  remote_user: root
  become: false

  roles:
    - git

- name: Install Docker
  hosts: all
  remote_user: root
  become: false

  roles:
    - docker